accounts/urls.py
from django.shortcuts import redirect
from django.urls import path, reverse
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    path("", lambda req: redirect(reverse('accounts:login'))),
    path("login/", auth_views.LoginView.as_view(template_name=app_name + "/login.html",
                                                next_page='fantasycalendar:world-index'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name=app_name + "/login.html",
                                                  next_page='fantasycalendar:world-index'), name="logout"),
    path("new/", views.UserCreateView.as_view(), name="user-create"),
]

fantasycalendar/urls.py
from django.shortcuts import redirect
from django.urls import path, reverse, include
from . import views
from rest_framework import routers
from . import api_views


router = routers.DefaultRouter()
router.register('worlds', api_views.WorldViewSet, 'world')
router.register('calendars', api_views.CalendarViewSet, 'calendar')
router.register('timeunits', api_views.TimeUnitViewSet, 'timeunit')
router.register('events', api_views.EventViewSet, 'event')
router.register('dateformats', api_views.DateFormatViewSet, 'dateformat')
router.register('displayconfigs', api_views.DisplayConfigViewSet, 'displayconfig')
router.register('datebookmarks', api_views.DateBookmarkViewSet, 'datebookmark')

app_name = 'fantasycalendar'
urlpatterns = [
    path("", lambda req: redirect(reverse('fantasycalendar:world-index'))),
    path("api/", include(router.urls)),
    path("api/userstatus/", api_views.UserStatus.as_view()),
    path("api/timeunitbaseinstances/", api_views.TimeUnitBaseInstances.as_view()),
    path("api/timeunitinstancedisplayname/", api_views.TimeUnitInstanceDisplayName.as_view()),
    path("api/timeunitequivalentiteration/", api_views.TimeUnitEquivalentIteration.as_view()),
    path("api/timeunitcontainediteration/", api_views.TimeUnitContainedIteration.as_view()),
    path("api/dateformatreverse/", api_views.DateFormatReverse.as_view()),
    path("api/datebookmarkcreatepersonal/", api_views.DateBookmarkCreatePersonal.as_view()),
    path("worlds/", views.WorldIndexView.as_view(), name="world-index"),
    path("worlds/<int:pk>/", views.WorldDetailView.as_view(), name="world-detail"),
    path("worlds/new/", views.WorldCreateView.as_view(), name="world-create"),
    path("worlds/<int:pk>/edit/", views.WorldUpdateView.as_view(), name="world-update"),
    path("worlds/<int:world_key>/calendars/<int:pk>/", views.CalendarDetailView.as_view(), name="calendar-detail"),
    path("worlds/<int:world_key>/calendars/new/", views.CalendarCreateView.as_view(), name="calendar-create"),
    path("worlds/<int:world_key>/calendars/<int:pk>/edit/", views.CalendarUpdateView.as_view(), name="calendar-update"),
    path("worlds/<int:world_key>/calendars/<int:pk>/calendar/", views.CalendarCalendarView.as_view(),
         name="calendar-calendar"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/time-units/<int:pk>/",
         views.TimeUnitDetailView.as_view(), name="time-unit-detail"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/time-units/new/", views.TimeUnitCreateView.as_view(),
         name="time-unit-create"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/time-units/<int:pk>/edit/",
         views.TimeUnitUpdateView.as_view(), name="time-unit-update"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/time-units/<int:pk>/instances/<int:iteration>/",
         views.TimeUnitInstanceDetailView.as_view(), name="time-unit-instance-detail"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/events/<int:pk>/", views.EventDetailView.as_view(),
         name="event-detail"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/events/new/", views.EventCreateView.as_view(),
         name="event-create"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/events/<int:pk>/edit/", views.EventUpdateView.as_view(),
         name="event-update"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/time-units/<int:timeunit_key>/date-formats/<int:pk>/",
         views.DateFormatDetailView.as_view(), name="date-format-detail"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/time-units/<int:timeunit_key>/date-formats/new/",
         views.DateFormatCreateView.as_view(), name="date-format-create"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/time-units/<int:timeunit_key>/date-formats/<int:pk>/"
         "edit/", views.DateFormatUpdateView.as_view(), name="date-format-update"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/display-configs/<int:pk>/",
         views.DisplayConfigDetailView.as_view(), name="display-config-detail"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/display-configs/new/",
         views.DisplayConfigCreateView.as_view(), name="display-config-create"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/display-configs/<int:pk>/edit/",
         views.DisplayConfigUpdateView.as_view(), name="display-config-update"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/display-configs/<int:display_config_key>/"
         "display-unit-configs/new/", views.DisplayUnitConfigCreateView.as_view(), name="display-unit-config-create"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/display-configs/<int:display_config_key>/"
         "display-unit-configs/<int:pk>/edit/", views.DisplayUnitConfigUpdateView.as_view(),
         name="display-unit-config-update"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/date-bookmarks/new/",
         views.DateBookmarkCreateView.as_view(), name="date-bookmark-create"),
    path("worlds/<int:world_key>/calendars/<int:calendar_key>/date-bookmarks/<int:pk>/edit/",
         views.DateBookmarkUpdateView.as_view(), name="date-bookmark-update"),
]

fcsite/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path("fantasy-calendar/", include("fantasycalendar.urls")),
    path("", lambda req: redirect('/fantasy-calendar/')),
]

fantasycalendar/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import World, Calendar, TimeUnit, Event, DateFormat, DisplayConfig, DateBookmark, DisplayUnitConfig
from .forms import DisplayConfigCreateForm, DisplayConfigUpdateForm, DisplayUnitConfigUpdateForm


class WorldIndexView(generic.ListView):
    model = World
    template_name = 'fantasycalendar/world_index.html'
    context_object_name = 'world_list'

    def get_queryset(self):
        worlds = World.objects.filter(public=True)
        if self.request.user.is_authenticated:
            worlds = worlds.exclude(creator_id=self.request.user.id)
        return worlds

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorldIndexView, self).get_context_data(object_list=object_list, **kwargs)
        if self.request.user.is_authenticated:
            context['user_world_list'] = World.objects.filter(creator_id=self.request.user.id)
        return context


class WorldDetailView(UserPassesTestMixin, generic.DetailView):
    model = World
    template_name = 'fantasycalendar/world_detail.html'

    def test_func(self):
        world = get_object_or_404(World, pk=self.kwargs['pk'])
        return world.public or self.request.user == world.creator


class CalendarDetailView(UserPassesTestMixin, generic.DetailView):
    model = Calendar
    template_name = 'fantasycalendar/calendar_detail.html'

    def test_func(self):
        world = get_object_or_404(World, pk=self.kwargs['world_key'])
        return world.public or self.request.user == world.creator

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'display_unit_type' in self.request.GET:
            context['display_unit'] = TimeUnit.objects.get(pk=self.request.GET['display_unit_type'])
        elif self.object.default_display_config:
            context['display_unit'] = self.object.default_display_config.display_unit
        else:
            self.object.ensure_bottom_level_time_unit()  # if unit not specified, it might not have one yet
            context['display_unit'] = TimeUnit.objects.filter(calendar_id=self.object.id).first()
        if 'nest_checkbox' in self.request.GET:
            context['nest_level'] = int(self.request.GET['nest_checkbox'])
        elif self.object.default_display_config:
            context['nest_level'] = self.object.default_display_config.nest_level
        else:
            context['nest_level'] = 0
        if 'iteration' in self.request.GET:
            context['iteration'] = int(self.request.GET['iteration'])
        elif self.object.default_display_config and self.object.default_display_config.default_date_bookmark:
            context['iteration'] = self.object.default_display_config.default_date_bookmark.bookmark_iteration
        else:
            context['iteration'] = 1

        context['instance_display_name'] = context['display_unit'].get_instance_display_name(context['iteration'])

        if context['nest_level'] > 0 and context['display_unit'].base_unit is not None and \
                context['display_unit'].base_unit.base_unit is not None:
            context['display_nested'] = True
            display_instances = context['display_unit'].get_base_unit_instances(iteration=context['iteration'])
            display_base_names = []
            nested_custom_names = context['display_unit'].base_unit.get_base_unit_instance_names()
            first_middle_instance_iteration = context['display_unit'].\
                get_first_base_unit_instance_iteration_at_iteration(iteration=context['iteration'])
            first_base_instance_iteration = context['display_unit'].base_unit.\
                get_first_base_unit_instance_iteration_at_iteration(iteration=first_middle_instance_iteration)
            for name, length in display_instances:
                nested_display_base_names = []
                for i in range(length):
                    if i < len(nested_custom_names):
                        nested_display_base_name = nested_custom_names[i]
                    else:
                        nested_display_base_name = str(context['display_unit'].base_unit.base_unit.time_unit_name) + \
                                                   ' ' + str(i + 1)
                    iteration = first_base_instance_iteration + i
                    events = context['display_unit'].base_unit.base_unit.get_events_at_iteration(iteration=iteration)
                    nested_display_base_names.append((nested_display_base_name, iteration, events))
                display_base_names.append((name, first_middle_instance_iteration, nested_display_base_names))
                first_middle_instance_iteration += 1
                first_base_instance_iteration += length
            context['display_base_names'] = display_base_names
            context['smallest_display_unit'] = context['display_unit'].base_unit.base_unit
        else:
            context['display_nested'] = False
            display_amount = int(context['display_unit'].get_length_at_iteration(iteration=context['iteration']))
            if display_amount < 1:
                display_amount = 1
            display_base_names = []
            if context['display_unit'].base_unit is not None:
                custom_names = context['display_unit'].get_base_unit_instance_names()
                first_base_instance_iteration = context['display_unit'].\
                    get_first_base_unit_instance_iteration_at_iteration(iteration=context['iteration'])
                for i in range(1, display_amount + 1):
                    if i - 1 < len(custom_names):
                        display_base_name = custom_names[i - 1]
                    else:
                        display_base_name = str(context['display_unit'].base_unit.time_unit_name) + ' ' + str(i)
                    iteration = first_base_instance_iteration + (i - 1)
                    events = context['display_unit'].base_unit.get_events_at_iteration(iteration=iteration)
                    display_base_names.append((display_base_name, iteration, events))
                context['smallest_display_unit'] = context['display_unit'].base_unit
            else:
                events = context['display_unit'].get_events_at_iteration(iteration=context['iteration'])
                display_base_names.append((context['display_unit'].time_unit_name + ' 1', context['iteration'], events))
                context['smallest_display_unit'] = context['display_unit']
            context['display_base_names'] = display_base_names

        return context


class CalendarCalendarView(UserPassesTestMixin, generic.DetailView):
    model = Calendar
    template_name = 'fantasycalendar/calendar_calendar.html'

    def test_func(self):
        world = get_object_or_404(World, pk=self.kwargs['world_key'])
        return world.public or self.request.user == world.creator


class TimeUnitDetailView(UserPassesTestMixin, generic.DetailView):
    model = TimeUnit
    template_name = 'fantasycalendar/time_unit_detail.html'

    def test_func(self):
        world = get_object_or_404(World, pk=self.kwargs['world_key'])
        return world.public or self.request.user == world.creator


class TimeUnitInstanceDetailView(UserPassesTestMixin, generic.DetailView):
    model = TimeUnit
    template_name = 'fantasycalendar/time_unit_instance_detail.html'

    def test_func(self):
        world = get_object_or_404(World, pk=self.kwargs['world_key'])
        return world.public or self.request.user == world.creator

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['iteration'] = self.kwargs['iteration']
        context['first_bottom_level_iteration'] = self.object.get_first_bottom_level_iteration_at_iteration(
            iteration=self.kwargs['iteration'])
        context['events'] = self.object.get_events_at_iteration(iteration=self.kwargs['iteration'])
        context['date_bookmarks'] = DateBookmark.objects.filter(bookmark_unit_id=self.object.id).\
            filter(bookmark_iteration=self.kwargs['iteration'])
        if self.object.default_date_format:
            context['display_name'] = self.object.default_date_format.get_formatted_date(self.kwargs['iteration'])
        else:
            context['display_name'] = str(self.object.time_unit_name) + ' ' + str(self.kwargs['iteration'])
        date_formats = DateFormat.objects.filter(time_unit_id=self.object.id)
        formatted_dates = [d.get_formatted_date(self.kwargs['iteration']) for d in date_formats]
        context['date_representations'] = [(df, fd) for df, fd in zip(date_formats, formatted_dates)]
        context['is_linked'] = self.object.is_linked()
        linked_instances = self.object.get_linked_instance_iterations(self.kwargs['iteration'])
        context['linked_instances'] = [(calendar.id, calendar.calendar_name, calendar.get_bottom_level_time_unit().id,
                                        iteration,
                                        calendar.get_bottom_level_time_unit().get_instance_display_name(iteration))
                                       for (calendar, iteration) in linked_instances]
        return context


class EventDetailView(UserPassesTestMixin, generic.DetailView):
    model = Event
    template_name = 'fantasycalendar/event_detail.html'

    def test_func(self):
        world = get_object_or_404(World, pk=self.kwargs['world_key'])
        return world.public or self.request.user == world.creator

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

fantasycalendar/templates/fantasycalendar/calendar_update_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Edit a Calendar
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

fantasycalendar/templates/fantasycalendar/date_bookmark_create_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Create a Date Bookmark
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

fantasycalendar/templates/fantasycalendar/date_bookmark_update_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Edit a Date Bookmark
{% endblock %}

{% block content %}
<h3>Bookmark for {{ datebookmark.bookmark_unit.time_unit_name }}</h3>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

fantasycalendar/templates/fantasycalendar/date_format_create_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Create a Date Format
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% include "fantasycalendar/format_string_helper.html" %}
{% endblock %}

fantasycalendar/templates/fantasycalendar/date_format_detail.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Date Format Detail
{% endblock %}

{% block content %}
<h2><a href="{% url 'fantasycalendar:world-detail' dateformat.calendar.world_id %}">{{ dateformat.calendar.world.world_name }}</a> - <a
        href="{% url 'fantasycalendar:calendar-detail' dateformat.calendar.world_id dateformat.calendar_id %}">{{ dateformat.calendar.calendar_name }}</a> - <a
        href="{% url 'fantasycalendar:time-unit-detail' dateformat.calendar.world_id dateformat.calendar_id dateformat.time_unit_id %}">{{ dateformat.time_unit.time_unit_name }}</a> - {{ dateformat.date_format_name }}{% if user.pk == dateformat.calendar.world.creator.pk %}
    <a href="{% url 'fantasycalendar:date-format-update' dateformat.calendar.world_id dateformat.calendar_id dateformat.time_unit_id dateformat.id %}">(edit)</a>{% endif %}</h2>
<h3>Format String:</h3>
<p>{{ dateformat.format_string }}</p>
{% endblock %}

fantasycalendar/templates/fantasycalendar/display_config_update_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Edit a Display Configuration
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

fantasycalendar/templates/fantasycalendar/event_detail.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Event Detail
{% endblock %}

{% block content %}
<h2><a href="{% url 'fantasycalendar:world-detail' event.calendar.world_id %}">{{ event.calendar.world.world_name }}</a> - <a
        href="{% url 'fantasycalendar:calendar-detail' event.calendar.world_id event.calendar_id %}">{{ event.calendar.calendar_name }}</a> - {{ event.event_name }}{% if user.pk == event.calendar.world.creator.pk %}
    <a href="{% url 'fantasycalendar:event-update' event.calendar.world_id event.calendar_id event.id %}">(edit)</a>{% endif %}</h2>
<h3>Event Description</h3>
<p>{{ event.event_description }}</p>
<h3>Takes Place on:</h3>
<p>{{ display_date }}</p>
{% endblock %}

fantasycalendar/templates/fantasycalendar/event_update_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Edit an Event
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

fantasycalendar/templates/fantasycalendar/login.html
{% extends "fantasycalendar/base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'fantasycalendar:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}

{% endblock %}

fantasycalendar/templates/fantasycalendar/time_unit_create_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Create a Time Unit
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

fantasycalendar/templates/fantasycalendar/time_unit_detail.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Time Unit Detail
{% endblock %}

{% block content %}
<h2><a href="{% url 'fantasycalendar:world-detail' timeunit.calendar.world_id %}">{{ timeunit.calendar.world.world_name }}</a> - <a
        href="{% url 'fantasycalendar:calendar-detail' timeunit.calendar.world_id timeunit.calendar_id %}">{{ timeunit.calendar.calendar_name }}</a> - {{ timeunit.time_unit_name }}{% if user.pk == timeunit.calendar.world.creator.pk %}
    <a href="{% url 'fantasycalendar:time-unit-update' timeunit.calendar.world_id timeunit.calendar_id timeunit.id %}">(edit)</a>{% endif %}</h2>
{% if timeunit.base_unit %}
    <h3>Base Unit</h3>
    <p><a href="{% url 'fantasycalendar:time-unit-detail' timeunit.calendar.world_id timeunit.calendar_id timeunit.base_unit.id %}">{{ timeunit.base_unit.time_unit_name }}</a></p>
    <h3>Length Cycle</h3>
    <p>{{ timeunit.get_length_cycle_display }}</p>
    {% if timeunit.base_unit_instance_names %}
        <h3>Base Unit Instance Names</h3>
        <ul>
            {% for base_name in timeunit.get_base_unit_instance_names %}
                <li>{{ base_name }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% else %}
    <h3>This is a Bottom Level Time Unit</h3>
{% endif %}
<h3>Date Formats{% if user.pk == timeunit.calendar.world.creator.pk %} <a href="{% url 'fantasycalendar:date-format-create' timeunit.calendar.world_id timeunit.calendar.id timeunit.id %}">(+new)</a>{% endif %}</h3>
{% if timeunit.dateformat_set %}
    <ul>
    {% for date_format in timeunit.dateformat_set.all %}
        <li><a href="{% url 'fantasycalendar:date-format-detail' timeunit.calendar.world_id timeunit.calendar.id timeunit.id date_format.id %}">{{ date_format.date_format_name }}</a>{% if user.pk == timeunit.calendar.world.creator.pk %} <a
                    href="{% url 'fantasycalendar:date-format-update' timeunit.calendar.world_id timeunit.calendar.id timeunit.id date_format.id %}">(edit)</a>{% endif %}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No date formats have been created for this calendar.</p>
{% endif %}
{% endblock %}

fantasycalendar/templates/fantasycalendar/world_create_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Create a World
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

fantasycalendar/templates/fantasycalendar/world_index.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
World Index
{% endblock %}

{% block content %}
<h3>My Worlds{% if user.is_authenticated %} <a href="{% url 'fantasycalendar:world-create' %}">(+new)</a>{% endif %}</h3>
{% if user.is_authenticated %}
    {% if user_world_list %}
        <ul>
        {% for world in user_world_list %}
            <li><a href="{% url 'fantasycalendar:world-detail' world.id %}">{{ world.world_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <ul>
            <li>You have not created any worlds yet. <a href="{% url 'fantasycalendar:world-create' %}">Make your first!</a></li>
        </ul>
    {% endif %}
{% else %}
    <ul>
        <li><a href="{% url 'accounts:login' %}">Log in</a> or <a href="{% url 'accounts:user-create' %}">make an account</a> to start creating!</li>
    </ul>
{% endif %}
<h3>Worlds from Other Creators</h3>
{% if world_list %}
    <ul>
    {% for world in world_list %}
        <li><a href="{% url 'fantasycalendar:world-detail' world.id %}">{{ world.world_name }}</a> by {{ world.creator.username }}</li>
    {% endfor %}
    </ul>
{% else %}
    <ul>
        <li>No public worlds {% if user.is_authenticated %}from other creators {% endif %}are available.</li>
    </ul>
{% endif %}
{% endblock %}

fantasycalendar/templates/fantasycalendar/world_update_form.html
{% extends "fantasycalendar/base.html" %}

{% block title %}
Edit a World
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}